/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package com.vg.hbase.manager.ui;

import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import org.apache.commons.lang.StringUtils;
import org.apache.hadoop.hbase.HColumnDescriptor;
import org.apache.hadoop.hbase.HTableDescriptor;
import org.apache.hadoop.hbase.client.HBaseAdmin;
import org.apache.hadoop.hbase.util.Bytes;

import com.vg.hbase.operations.base.HBaseConfigurationManager;

/**
 * 
 * @author skrishnanunni
 */
public class HBaseManagerTableDesign extends javax.swing.JDialog {
    
    /**
     * 
     */
    private static final long serialVersionUID = 366535590568661722L;
    /**
     * Creates new form HBaseManagerTableDesign
     */
    
    private static DefaultListModel listModel;
    // HashMap<String,int> versionList = new HashMap<String, int>();
    HashMap<String, String> versions = new HashMap<String, String>();
    
    public HBaseManagerTableDesign(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
	listModel = (DefaultListModel) this.listColFamilynames.getModel();
	
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents() {
	
	jPanel2 = new javax.swing.JPanel();
	jLabel1 = new javax.swing.JLabel();
	valueNewColFamilyName = new javax.swing.JTextField();
	jLabel2 = new javax.swing.JLabel();
	valueNewTableName = new javax.swing.JTextField();
	jScrollPane1 = new javax.swing.JScrollPane();
	listColFamilynames = new javax.swing.JList(new DefaultListModel());
	clickAddColFamily = new javax.swing.JButton();
	jLabel3 = new javax.swing.JLabel();
	clickCreateTable = new javax.swing.JButton();
	clickCancel = new javax.swing.JButton();
	clickRemoveColFamily = new javax.swing.JButton();
	valueVersions = new javax.swing.JTextField();
	jLabel4 = new javax.swing.JLabel();
	
	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	setTitle("HBase Manager: New Table");
	setAlwaysOnTop(true);
	
	jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	
	jLabel1.setText("New Table Name : ");
	
	jLabel2.setText("Coloumn Families :");
	
	jScrollPane1.setViewportView(listColFamilynames);
	
	clickAddColFamily.setText("Add Coloumn Family");
	clickAddColFamily.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		clickAddColFamilyActionPerformed(evt);
	    }
	});
	
	jLabel3.setText("New Coloumn Family:");
	
	clickCreateTable.setText("Create Table");
	clickCreateTable.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		clickCreateTableActionPerformed(evt);
	    }
	});
	
	clickCancel.setText("Cancel");
	clickCancel.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		clickCancelActionPerformed(evt);
	    }
	});
	
	clickRemoveColFamily.setText("Remove CF");
	clickRemoveColFamily.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		clickRemoveColFamilyActionPerformed(evt);
	    }
	});
	
	jLabel4.setText("Max versions");
	
	javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	jPanel2.setLayout(jPanel2Layout);
	jPanel2Layout
		.setHorizontalGroup(jPanel2Layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel2Layout
					.createSequentialGroup()
					.addGap(28, 28, 28)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addComponent(jLabel3).addComponent(jLabel2)
							.addComponent(jLabel1).addComponent(jLabel4))
					.addGap(18, 18, 18)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
							.addGroup(
								jPanel2Layout
									.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(valueNewTableName,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										207,
										javax.swing.GroupLayout.PREFERRED_SIZE)
									.addGroup(
										jPanel2Layout
											.createSequentialGroup()
											.addComponent(
												valueNewColFamilyName,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												115,
												javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(clickAddColFamily))
									.addComponent(valueVersions,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										53,
										javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(
								jPanel2Layout
									.createSequentialGroup()
									.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										113,
										javax.swing.GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addComponent(clickRemoveColFamily,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										136,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(30, Short.MAX_VALUE))
			.addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout.createSequentialGroup()
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(clickCreateTable).addGap(28, 28, 28).addComponent(clickCancel)
					.addGap(104, 104, 104)));
	jPanel2Layout
		.setVerticalGroup(jPanel2Layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(
				jPanel2Layout
					.createSequentialGroup()
					.addGap(25, 25, 25)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(jLabel1)
							.addComponent(valueNewTableName,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addGap(29, 29, 29)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(valueNewColFamilyName,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(clickAddColFamily).addComponent(jLabel3))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(valueVersions,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
							.addComponent(jLabel4))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33,
						Short.MAX_VALUE)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(
								jPanel2Layout
									.createSequentialGroup()
									.addGap(0, 0, Short.MAX_VALUE)
									.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
							.addGroup(
								jPanel2Layout
									.createSequentialGroup()
									.addComponent(jLabel2)
									.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
									.addComponent(clickRemoveColFamily)))
					.addGap(39, 39, 39)
					.addGroup(
						jPanel2Layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent(clickCreateTable).addComponent(clickCancel))
					.addGap(29, 29, 29)));
	
	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		layout.createSequentialGroup()
			.addContainerGap()
			.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
			.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
		javax.swing.GroupLayout.Alignment.TRAILING,
		layout.createSequentialGroup()
			.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
			.addContainerGap()));
	
	pack();
    }// </editor-fold>
    
    private void clickAddColFamilyActionPerformed(java.awt.event.ActionEvent evt) {
	
	String splchars = "`~!@#$%^&*()_+=,./<>?;':\"\\ \n";
	char[] splCharArray = splchars.toCharArray();
	String colFamilyName = valueNewColFamilyName.getText();
	int maxVersion = Integer.parseInt(valueVersions.getText());
	if (maxVersion > 0) {
	    versions.put(colFamilyName, String.valueOf(maxVersion));
	    
	} else {
	    versions.put(colFamilyName, "1");
	}
	
	if (StringUtils.isEmpty(colFamilyName) || StringUtils.containsAny(colFamilyName, splCharArray)) {
	    JOptionPane.showMessageDialog(this, "Provide a valid Coloumn Family Name");
	} else {
	    listModel.addElement(colFamilyName);
	}
    }
    
    private void clickCreateTableActionPerformed(java.awt.event.ActionEvent evt) {
	
	HBaseAdmin admin = HBaseConfigurationManager.getHbaseAdmin();
	HTableDescriptor tableDesc = new HTableDescriptor();
	HColumnDescriptor familyDesc;
	tableDesc.setName(Bytes.toBytes(valueNewTableName.getText()));
	String colFamName;
	int version;
	
	for (int i = 0; i < listModel.getSize(); i++) {
	    colFamName = (String) listModel.getElementAt(i);
	    version = Integer.parseInt(versions.get(colFamName));
	    familyDesc = new HColumnDescriptor(colFamName);
	    familyDesc.setMaxVersions(version);
	    
	    System.out.println("Adding Family: " + colFamName);
	    tableDesc.addFamily(familyDesc);
	    
	}
	try {
	    admin.createTable(tableDesc);
	}
	catch (IOException ex) {
	    JOptionPane.showMessageDialog(this, "Table Creation Failed", "Error", JOptionPane.ERROR_MESSAGE);
	    Logger.getLogger(HBaseManagerTableDesign.class.getName()).log(Level.SEVERE, null, ex);
	}
	
    }
    
    private void clickCancelActionPerformed(java.awt.event.ActionEvent evt) {
	
	this.dispose();
    }
    
    private void clickRemoveColFamilyActionPerformed(java.awt.event.ActionEvent evt) {
	
	versions.remove((String) listColFamilynames.getSelectedValue());
	listModel.remove(listColFamilynames.getSelectedIndex());
    }
    
    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase
	 * /tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	}
	catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(HBaseManagerTableDesign.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(HBaseManagerTableDesign.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(HBaseManagerTableDesign.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(HBaseManagerTableDesign.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	// </editor-fold>
	
	/*
	 * Create and display the dialog
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    
	    public void run() {
		HBaseManagerTableDesign dialog = new HBaseManagerTableDesign(new javax.swing.JFrame(), true);
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		    
		    @Override
		    public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
		    }
		});
		dialog.setVisible(true);
	    }
	});
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton clickAddColFamily;
    private javax.swing.JButton clickCancel;
    private javax.swing.JButton clickCreateTable;
    private javax.swing.JButton clickRemoveColFamily;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listColFamilynames;
    private javax.swing.JTextField valueNewColFamilyName;
    private javax.swing.JTextField valueNewTableName;
    private javax.swing.JTextField valueVersions;
    // End of variables declaration
}
